### ISSUE TITLE
Loading doesn't work as documentation suggests.

### ISSUE THREAD

**Issue by calebuharrison** [AliOsm/phlex-icons#19]
Hello! Thanks for putting this gem together.

Just wanted to give you a heads up that loading doesn't seem to work as described in the README. The gem is not loaded automatically on boot (in rails) and trying to `require "phlex-icons"` throws an uninitialized constant error.

Looks like this was a regression from "0.15.0" to "0.16.0".

**Comment by AliOsm** [comment]
Hmmm this is weird, I'm using the gem in 2 Rails apps following the README and all works fine. Let me test on a fresh Rails app. What is the Rails/Phlex versions you are using?

**Comment by AliOsm** [comment]
Also, are you using `phlex-icons` or the pack specific gems (e.g. `phlex-icons-bootstrap`)?

**Comment by AliOsm** [comment]
@calebuharrison any updates on this?

**Comment by calebuharrison** [comment]
@AliOsm Sorry for the drive-by issue submission! Haven't had a chance to revisit this yet - feel free to close if you're unable to reproduce. If I hit this again, I'll be sure to provide more info.

**Comment by ascruggs** [comment]
FWIW, I have the same issue.  I had to use `require 'phlex_icons'` to get it to load

**Comment by ascruggs** [comment]
I wish I had more to offer.  I am on a rails 7.1 project.  After manually changing the version to 1.1.0, I was able to `include Phlex::Icons`. That said, I got an `uninitialized constant` error trying to use Phlex Kit or just trying to do a regular `render`

**Comment by AliOsm** [comment]
@ascruggs sorry for the late reply, I need to configure the email notifications currectly 😁

The main blocker for me is that I can't re-produce the issue. Could you please create a Rails app that has the issue and share it with me ?,?

I'm saying that because I'm using `phlex-icons` with 3 projects all in production without issues, and I really want to solve the hidden issue of uninitialized constants mentioned above 🫠

**Comment by AliOsm** [comment]
@ascruggs If you have more info on the error itself like logs, and similar, could you please share.

**Comment by AliOsm** [comment]
Resolving as I can't reproduce the issue.
