### ISSUE TITLE
Parallelize components generation

### ISSUE THREAD

**Issue by AliOsm** [AliOsm/phlex-icons#5]
In all generators, there is a loop that generates icon components sequentially. This loop is very slow, specially when the icon pack has a lot of icons (e.g. Bootstrap Icons are 2,000+, takes ~30 minutes to complete the generation). This loop should be parallelized, in all generators.

**Comment by AliOsm** [comment]
Example: https://github.com/AliOsm/phlex-icons/blob/main/generators%2Fbootstrap_icons.rb#L٤٧

**Comment by AliOsm** [comment]
Looks like the issue was running RuboCop for each file individually. Now I'm testing running RuboCop after finalizing the components creation, and it is still slow, but better than before. The conclusion is: RuboCop is the root cause :3

**Comment by AliOsm** [comment]
Generating Bootstrap icons (2,050) is taking ~2 minutes now, after running RuboCop 1 time on all file. I will close this issue for now.

**Comment by IbraheemTuffaha** [comment]
Very nice, thank you for taking care of this.
I was wondering, why not remove the empty 'class' attribute (cleaner)?
And add some width or height to the icons? I see icons websites do that
